# Generated by Django 4.2.7 on 2025-08-02 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Benutzer', 'verbose_name_plural': 'Benutzer'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Abrechnungs-E-Mail'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_use_analytics',
            field=models.BooleanField(default=False, verbose_name='Analytics verfügbar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_use_api',
            field=models.BooleanField(default=False, verbose_name='API-Zugang verfügbar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_use_content_library',
            field=models.BooleanField(default=False, verbose_name='Content-Bibliothek verfügbar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_use_premium_templates',
            field=models.BooleanField(default=False, verbose_name='Premium Templates verfügbar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_use_white_label',
            field=models.BooleanField(default=False, verbose_name='White-Label verfügbar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Firmenname'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dealroom_limit',
            field=models.PositiveIntegerField(default=3, verbose_name='Dealroom Limit'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin_account',
            field=models.BooleanField(default=False, verbose_name='Admin Account für Abrechnung'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Plan End Datum'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Plan Start Datum'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='USt-IdNr.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
    ]
