# Generated by Django 4.2.7 on 2025-08-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_remove_customuser_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='analytics_opt_in',
            field=models.BooleanField(default=False, help_text='Ich stimme zu, dass anonymisierte Nutzungsdaten für die Produktoptimierung verwendet werden dürfen.', verbose_name='Analytics-Opt-In (DSGVO-konform)'),
        ),
    ]
