# Generated by Django 4.2.7 on 2025-08-03 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_analytics_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20, verbose_name='Benutzerrolle'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plan_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Plan End Datum'),
        ),
    ]
