# Generated by Django 5.2.4 on 2025-07-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('active', 'Aktiv'), ('inactive', 'Inaktiv'), ('archived', 'Archiviert')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Firmenname')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Branche')),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investitionsbetrag')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Währung')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Kontakt E-Mail')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kontakt Telefon')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('file', models.FileField(upload_to='deal_files/', verbose_name='Datei')),
                ('file_type', models.CharField(choices=[('image', 'Bild'), ('document', 'Dokument'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Dateityp')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('is_public', models.BooleanField(default=True, verbose_name='Öffentlich')),
            ],
            options={
                'verbose_name': 'Deal-Datei',
                'verbose_name_plural': 'Deal-Dateien',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template-Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('template_file', models.FileField(upload_to='templates/', verbose_name='Template-Datei')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/', verbose_name='Vorschau-Bild')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['name'],
            },
        ),
    ]
