# Generated by Django 5.2.4 on 2025-07-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='template',
        ),
        migrations.AddField(
            model_name='deal',
            name='call_to_action',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Call-to-Action Text'),
        ),
        migrations.AddField(
            model_name='deal',
            name='hero_subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Hero-Untertitel'),
        ),
        migrations.AddField(
            model_name='deal',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hero-Titel'),
        ),
        migrations.AddField(
            model_name='deal',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160, null=True, verbose_name='Meta-Beschreibung'),
        ),
        migrations.AddField(
            model_name='deal',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Meta-Titel'),
        ),
        migrations.AddField(
            model_name='deal',
            name='primary_color',
            field=models.CharField(default='#0d6efd', max_length=7, verbose_name='Primärfarbe'),
        ),
        migrations.AddField(
            model_name='deal',
            name='public_url',
            field=models.URLField(blank=True, null=True, verbose_name='Öffentliche URL'),
        ),
        migrations.AddField(
            model_name='deal',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='Sekundärfarbe'),
        ),
        migrations.AddField(
            model_name='deal',
            name='template_type',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Klassisch'), ('minimal', 'Minimalistisch'), ('corporate', 'Corporate'), ('creative', 'Kreativ')], default='modern', max_length=20, verbose_name='Template-Typ'),
        ),
        migrations.AddField(
            model_name='dealfile',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primär (für Hero/Logo)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL-Slug'),
        ),
        migrations.AlterField(
            model_name='dealfile',
            name='file_type',
            field=models.CharField(choices=[('hero_image', 'Hero-Bild'), ('logo', 'Logo'), ('gallery', 'Galerie'), ('document', 'Dokument'), ('video', 'Video'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Dateityp'),
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
