# Generated by Django 5.2.4 on 2025-08-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0003_remove_deal_template_deal_call_to_action_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="investment_amount",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="website",
        ),
        migrations.AddField(
            model_name="deal",
            name="access_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Zugriffsanzahl"),
        ),
        migrations.AddField(
            model_name="deal",
            name="central_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dealroom_videos/",
                verbose_name="Zentrales Video (Datei)",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="central_video_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Zentrales Video (YouTube/Vimeo)"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="customer_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Kunden E-Mail"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="customer_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="Informationen zum Kunden"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="customer_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Kundenname"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="generation_error",
            field=models.TextField(
                blank=True, null=True, verbose_name="Generierungsfehler"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="last_accessed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Letzter Zugriff"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="last_generation",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Letzte Generierung"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="local_website_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Lokale Website-URL"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="recipient_company",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Empfänger Firma"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="recipient_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Empfänger E-Mail"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="recipient_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Empfänger Name"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="website_status",
            field=models.CharField(
                choices=[
                    ("not_generated", "Nicht generiert"),
                    ("generating", "Wird generiert"),
                    ("generated", "Generiert"),
                    ("failed", "Generierung fehlgeschlagen"),
                ],
                default="not_generated",
                max_length=20,
                verbose_name="Website-Status",
            ),
        ),
    ]
