# Generated by Django 5.2.4 on 2025-08-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0004_remove_deal_contact_email_remove_deal_contact_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="hero_data_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dealroom_hero_data/",
                verbose_name="Hero-Daten (Datei)",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="recipient_logo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dealroom_logos/",
                verbose_name="Empfänger Logo",
            ),
        ),
    ]
