# Generated by Django 5.2.4 on 2025-08-02 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0005_deal_hero_data_file_deal_recipient_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="hero_data_file",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="recipient_logo",
        ),
    ]
