# Generated by Django 5.2.4 on 2025-08-02 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0006_remove_deal_hero_data_file_and_more"),
        ("files", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DealFileAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Zugeordnet am"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("hero_image", "Hero-Bild"),
                            ("logo", "Logo"),
                            ("gallery", "Galerie"),
                            ("document", "Dokument"),
                            ("video", "Video"),
                            ("data", "Daten"),
                            ("other", "Sonstiges"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Rolle",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Reihenfolge"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Zugeordnet von",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_assignments",
                        to="deals.deal",
                        verbose_name="Dealroom",
                    ),
                ),
                (
                    "global_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_assignments",
                        to="files.globalfile",
                        verbose_name="Globale Datei",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealroom-Datei-Zuordnung",
                "verbose_name_plural": "Dealroom-Datei-Zuordnungen",
                "ordering": ["order", "assigned_at"],
                "unique_together": {("deal", "global_file")},
            },
        ),
    ]
