# Generated by Django 5.2.4 on 2025-08-02 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0007_dealfileassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DealChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Erstellt"),
                            ("updated", "Aktualisiert"),
                            ("deleted", "Gelöscht"),
                            ("file_assigned", "Datei zugeordnet"),
                            ("file_unassigned", "Datei entfernt"),
                            ("status_changed", "Status geändert"),
                            ("website_generated", "Website generiert"),
                            ("website_deleted", "Website gelöscht"),
                        ],
                        max_length=50,
                        verbose_name="Änderungstyp",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Geändert am"),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Feldname"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, null=True, verbose_name="Alter Wert"),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, null=True, verbose_name="Neuer Wert"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geändert von",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="deals.deal",
                        verbose_name="Dealroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealroom-Änderung",
                "verbose_name_plural": "Dealroom-Änderungen",
                "ordering": ["-changed_at"],
            },
        ),
    ]
