# Generated by Django 5.2.4 on 2025-08-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0008_dealchangelog"),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealfile",
            name="file_source",
            field=models.CharField(
                choices=[
                    ("uploaded", "Direkt hochgeladen"),
                    ("global_assigned", "Globale Datei zugeordnet"),
                ],
                default="uploaded",
                max_length=20,
                verbose_name="Datei-Quelle",
            ),
        ),
        migrations.AddField(
            model_name="dealfile",
            name="global_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deal_file_references",
                to="files.globalfile",
                verbose_name="Globale Datei",
            ),
        ),
        migrations.AlterField(
            model_name="dealfile",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="deal_files/", verbose_name="Datei"
            ),
        ),
    ]
