# Generated by Django 5.2.4 on 2025-08-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0009_dealfile_file_source_dealfile_global_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="title",
            field=models.CharField(max_length=200, unique=True, verbose_name="Titel"),
        ),
    ]
