# Generated by Django 4.2.7 on 2025-08-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_add_unique_title_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Ansprechpartner E-Mail'),
        ),
        migrations.AddField(
            model_name='deal',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ansprechpartner Name'),
        ),
        migrations.AddField(
            model_name='deal',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ansprechpartner Telefon'),
        ),
        migrations.AddField(
            model_name='deal',
            name='customer_logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Kunden-Logo URL'),
        ),
        migrations.AddField(
            model_name='deal',
            name='customer_tasks',
            field=models.JSONField(blank=True, default=list, verbose_name='Kunden-Aufgaben'),
        ),
        migrations.AddField(
            model_name='deal',
            name='deal_progress',
            field=models.PositiveIntegerField(default=0, verbose_name='Deal-Fortschritt (%)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='deal_status',
            field=models.CharField(choices=[('initial', 'Initial'), ('offer_review', 'Angebot in Prüfung'), ('contract_prepared', 'Vertragsdaten bereitgestellt'), ('pending_signature', 'Unterschrift ausstehend'), ('completed', 'Abgeschlossen')], default='initial', max_length=50, verbose_name='Deal-Status'),
        ),
        migrations.AddField(
            model_name='deal',
            name='faq_items',
            field=models.JSONField(blank=True, default=list, verbose_name='FAQ-Elemente'),
        ),
        migrations.AddField(
            model_name='deal',
            name='theme_type',
            field=models.CharField(choices=[('light', 'Hell'), ('dark', 'Dunkel'), ('auto', 'Automatisch (System)')], default='light', max_length=10, verbose_name='Theme-Typ'),
        ),
        migrations.AddField(
            model_name='deal',
            name='timeline_events',
            field=models.JSONField(blank=True, default=list, verbose_name='Timeline-Ereignisse'),
        ),
        migrations.AddField(
            model_name='deal',
            name='welcome_message',
            field=models.TextField(blank=True, null=True, verbose_name='Willkommensnachricht'),
        ),
    ]
