# Generated by Django 4.2.7 on 2025-08-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_deal_contact_person_email_deal_contact_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='document_access_levels',
            field=models.JSONField(blank=True, default=list, verbose_name='Dokumentenzugriffsebenen'),
        ),
        migrations.AddField(
            model_name='deal',
            name='document_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='Dokumentenkategorien'),
        ),
        migrations.AddField(
            model_name='deal',
            name='product_currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Währung'),
        ),
        migrations.AddField(
            model_name='deal',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='Produktbeschreibung'),
        ),
        migrations.AddField(
            model_name='deal',
            name='product_features',
            field=models.JSONField(blank=True, default=list, verbose_name='Produktfeatures'),
        ),
        migrations.AddField(
            model_name='deal',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Produktname'),
        ),
        migrations.AddField(
            model_name='deal',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Produktpreis'),
        ),
        migrations.AddField(
            model_name='dealfile',
            name='document_access_level',
            field=models.CharField(choices=[('public', 'Öffentlich'), ('customer', 'Nur Kunde'), ('internal', 'Intern'), ('confidential', 'Vertraulich')], default='public', max_length=20, verbose_name='Zugriffsebene'),
        ),
        migrations.AddField(
            model_name='dealfile',
            name='document_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dokumentenkategorie'),
        ),
        migrations.AddField(
            model_name='dealfile',
            name='document_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ablaufdatum'),
        ),
        migrations.AddField(
            model_name='dealfile',
            name='document_requires_signature',
            field=models.BooleanField(default=False, verbose_name='Unterschrift erforderlich'),
        ),
        migrations.AddField(
            model_name='dealfile',
            name='document_version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Dokumentversion'),
        ),
        migrations.AlterField(
            model_name='dealfile',
            name='file_type',
            field=models.CharField(choices=[('hero_image', 'Hero-Bild'), ('logo', 'Logo'), ('gallery', 'Galerie'), ('document', 'Dokument'), ('contract', 'Vertrag'), ('offer', 'Angebot'), ('invoice', 'Rechnung'), ('presentation', 'Präsentation'), ('specification', 'Spezifikation'), ('video', 'Video'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Dateityp'),
        ),
    ]
