# Generated by Django 4.2.7 on 2025-08-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_deal_document_access_levels_deal_document_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Zusätzliches CSS für die Website', null=True, verbose_name='Benutzerdefiniertes CSS'),
        ),
        migrations.AddField(
            model_name='deal',
            name='custom_html_body_end',
            field=models.TextField(blank=True, help_text='HTML-Code vor dem </body> Tag (Footer, Scripts, etc.)', null=True, verbose_name='Benutzerdefinierter HTML-Body-End'),
        ),
        migrations.AddField(
            model_name='deal',
            name='custom_html_body_start',
            field=models.TextField(blank=True, help_text='HTML-Code nach dem <body> Tag (Navigation, etc.)', null=True, verbose_name='Benutzerdefinierter HTML-Body-Start'),
        ),
        migrations.AddField(
            model_name='deal',
            name='custom_html_content',
            field=models.TextField(blank=True, help_text='HTML-Code für den Hauptinhalt (ersetzt automatisch generierten Content)', null=True, verbose_name='Benutzerdefinierter HTML-Content'),
        ),
        migrations.AddField(
            model_name='deal',
            name='custom_html_header',
            field=models.TextField(blank=True, help_text='HTML-Code für den <head> Bereich (CSS, Meta-Tags, etc.)', null=True, verbose_name='Benutzerdefinierter HTML-Header'),
        ),
        migrations.AddField(
            model_name='deal',
            name='custom_javascript',
            field=models.TextField(blank=True, help_text='Zusätzliches JavaScript für die Website', null=True, verbose_name='Benutzerdefiniertes JavaScript'),
        ),
        migrations.AddField(
            model_name='deal',
            name='html_edit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Anzahl HTML-Bearbeitungen'),
        ),
        migrations.AddField(
            model_name='deal',
            name='html_editor_mode',
            field=models.CharField(choices=[('auto', 'Automatisch generiert'), ('manual', 'Manuell bearbeitet'), ('hybrid', 'Hybrid (Auto + Manuell)')], default='auto', max_length=20, verbose_name='HTML-Editor-Modus'),
        ),
        migrations.AddField(
            model_name='deal',
            name='last_html_edit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte HTML-Bearbeitung'),
        ),
    ]
