# Generated by Django 4.2.7 on 2025-08-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_deal_custom_css_deal_custom_html_body_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='password_protection_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Passwortversuche'),
        ),
        migrations.AddField(
            model_name='deal',
            name='password_protection_block_duration',
            field=models.PositiveIntegerField(default=15, help_text='Dauer der Sperrung nach zu vielen Versuchen', verbose_name='Sperrdauer (Minuten)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='password_protection_blocked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gesperrt bis'),
        ),
        migrations.AddField(
            model_name='deal',
            name='password_protection_enabled',
            field=models.BooleanField(default=False, verbose_name='Passwortschutz aktiviert'),
        ),
        migrations.AddField(
            model_name='deal',
            name='password_protection_last_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzter Passwortversuch'),
        ),
        migrations.AddField(
            model_name='deal',
            name='password_protection_log_attempts',
            field=models.BooleanField(default=True, help_text='Protokolliert alle Passwortversuche für Sicherheitsanalysen', verbose_name='Passwortversuche protokollieren'),
        ),
        migrations.AddField(
            model_name='deal',
            name='password_protection_max_attempts',
            field=models.PositiveIntegerField(default=5, help_text='Anzahl der erlaubten Versuche bevor der Zugriff gesperrt wird', verbose_name='Maximale Passwortversuche'),
        ),
        migrations.AddField(
            model_name='deal',
            name='password_protection_message',
            field=models.TextField(blank=True, default='Diese Landingpage ist passwortgeschützt. Bitte geben Sie das Passwort ein.', help_text='Benutzerdefinierte Nachricht für die Passwortabfrage', null=True, verbose_name='Passwortschutz-Nachricht'),
        ),
        migrations.AddField(
            model_name='deal',
            name='password_protection_password',
            field=models.CharField(blank=True, help_text='Passwort für den Zugriff auf die Landingpage (wird verschlüsselt gespeichert)', max_length=128, null=True, verbose_name='Passwortschutz-Passwort'),
        ),
    ]
