# Generated by Django 4.2.7 on 2025-08-02 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0014_deal_password_protection_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='random_url_code',
            field=models.CharField(blank=True, help_text='Automatisch generierter Code für sichere URLs', max_length=12, null=True, unique=True, verbose_name='Random-URL-Code'),
        ),
        migrations.AddField(
            model_name='deal',
            name='url_type',
            field=models.CharField(choices=[('friendly', 'Benutzerfreundlich (Name-basiert)'), ('random', 'Random-Nummern (Sicher)')], default='friendly', help_text='Benutzerfreundliche URLs oder sichere Random-Nummern', max_length=20, verbose_name='URL-Typ'),
        ),
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('media_type', models.CharField(choices=[('image', 'Bild'), ('video', 'Video'), ('document', 'Dokument'), ('logo', 'Logo'), ('icon', 'Icon'), ('other', 'Sonstiges')], max_length=20, verbose_name='Medien-Typ')),
                ('category', models.CharField(choices=[('general', 'Allgemein'), ('corporate', 'Corporate'), ('product', 'Produkt'), ('team', 'Team'), ('background', 'Hintergrund'), ('custom', 'Benutzerdefiniert')], default='general', max_length=50, verbose_name='Kategorie')),
                ('file', models.FileField(upload_to='media_library/', verbose_name='Datei')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('alt_text', models.CharField(blank=True, help_text='Für Barrierefreiheit', max_length=200, null=True, verbose_name='Alt-Text')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Verwendungsanzahl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Medien-Bibliothek',
                'verbose_name_plural': 'Medien-Bibliothek',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LayoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('layout_type', models.CharField(choices=[('single_column', 'Einspaltig'), ('two_column', 'Zweispaltig'), ('three_column', 'Dreispaltig'), ('grid', 'Grid-Layout'), ('hero_focus', 'Hero-Fokus'), ('content_focus', 'Content-Fokus'), ('custom', 'Benutzerdefiniert')], max_length=50, verbose_name='Layout-Typ')),
                ('category', models.CharField(choices=[('general', 'Allgemein'), ('corporate', 'Corporate'), ('creative', 'Kreativ'), ('minimal', 'Minimalistisch'), ('modern', 'Modern'), ('custom', 'Benutzerdefiniert')], default='general', max_length=50, verbose_name='Kategorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('css_classes', models.TextField(blank=True, help_text='CSS-Klassen für das Layout', null=True, verbose_name='CSS-Klassen')),
                ('html_structure', models.TextField(blank=True, help_text='HTML-Grundstruktur für das Layout', null=True, verbose_name='HTML-Struktur')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='layout_previews/', verbose_name='Vorschau-Bild')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Verwendungsanzahl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Layout-Vorlage',
                'verbose_name_plural': 'Layout-Vorlagen',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('content_type', models.CharField(choices=[('welcome', 'Begrüßung'), ('product_description', 'Produktbeschreibung'), ('faq_item', 'FAQ-Eintrag'), ('cta_text', 'Call-to-Action'), ('footer_info', 'Footer-Information'), ('contact_info', 'Kontaktinformation'), ('deal_status', 'Deal-Status'), ('task_description', 'Aufgabenbeschreibung'), ('timeline_event', 'Timeline-Ereignis'), ('custom', 'Benutzerdefiniert')], max_length=50, verbose_name='Content-Typ')),
                ('category', models.CharField(choices=[('general', 'Allgemein'), ('software', 'Software'), ('consulting', 'Beratung'), ('marketing', 'Marketing'), ('sales', 'Vertrieb'), ('support', 'Support'), ('custom', 'Benutzerdefiniert')], default='general', max_length=50, verbose_name='Kategorie')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('description', models.TextField(blank=True, help_text='Kurze Beschreibung für die Auswahl', null=True, verbose_name='Beschreibung')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags für bessere Kategorisierung', verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Verwendungsanzahl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Content-Block',
                'verbose_name_plural': 'Content-Blöcke',
                'ordering': ['category', 'title'],
            },
        ),
    ]
