# Generated by Django 4.2.7 on 2025-08-02 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0015_deal_random_url_code_deal_url_type_medialibrary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Deal erstellt'), ('deleted', 'Deal gelöscht'), ('updated', 'Deal bearbeitet')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='deals.deal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deal-Analytics-Event',
                'verbose_name_plural': 'Deal-Analytics-Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
