# Generated by Django 4.2.7 on 2025-08-02 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0016_dealanalyticsevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('element_type', models.CharField(choices=[('container', 'Container'), ('row', 'Zeile'), ('column', 'Spalte'), ('section', 'Sektion'), ('heading', 'Überschrift'), ('paragraph', 'Absatz'), ('list', 'Liste'), ('quote', 'Zitat'), ('image', 'Bild'), ('video', 'Video'), ('icon', 'Icon'), ('gallery', 'Galerie'), ('button', 'Button'), ('link', 'Link'), ('form', 'Formular'), ('map', 'Karte'), ('card', 'Karte'), ('table', 'Tabelle'), ('timeline', 'Zeitlinie'), ('stats', 'Statistiken'), ('social_share', 'Social Share'), ('comments', 'Kommentare'), ('rating', 'Bewertung'), ('follow', 'Follow'), ('accordion', 'Akkordeon'), ('tabs', 'Tabs'), ('modal', 'Modal'), ('slider', 'Slider'), ('file_download', 'Datei-Download'), ('document_viewer', 'Dokument-Viewer'), ('data_table', 'Daten-Tabelle'), ('progress_tracker', 'Fortschritt-Tracker')], max_length=50, verbose_name='Element-Typ')),
                ('category', models.CharField(choices=[('layout', 'Layout'), ('text', 'Text'), ('media', 'Medien'), ('interactive', 'Interaktiv'), ('business', 'Business'), ('social', 'Social'), ('advanced', 'Erweitert'), ('data', 'Daten & Dateien')], max_length=50, verbose_name='Kategorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('html_template', models.TextField(help_text='HTML-Code für das Element', verbose_name='HTML-Template')),
                ('css_styles', models.TextField(blank=True, help_text='Zusätzliche CSS-Styles', null=True, verbose_name='CSS-Styles')),
                ('javascript_code', models.TextField(blank=True, help_text='JavaScript für Interaktivität', null=True, verbose_name='JavaScript-Code')),
                ('data_source', models.CharField(choices=[('static', 'Statisch'), ('deal_data', 'Deal-Daten'), ('file_library', 'Datei-Bibliothek'), ('content_blocks', 'Content-Blöcke'), ('media_library', 'Medien-Bibliothek'), ('custom', 'Benutzerdefiniert')], default='static', max_length=50, verbose_name='Datenquelle')),
                ('data_mapping', models.JSONField(blank=True, default=dict, help_text='Mapping für dynamische Daten', verbose_name='Daten-Mapping')),
                ('file_types', models.JSONField(blank=True, default=list, help_text='Liste der unterstützten Dateitypen', verbose_name='Unterstützte Dateitypen')),
                ('file_upload_enabled', models.BooleanField(default=False, verbose_name='Datei-Upload aktiviert')),
                ('file_display_mode', models.CharField(choices=[('inline', 'Inline'), ('download', 'Download'), ('preview', 'Vorschau'), ('gallery', 'Galerie')], default='inline', max_length=20, verbose_name='Datei-Anzeigemodus')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Verwendungsanzahl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'CMS-Element',
                'verbose_name_plural': 'CMS-Elemente',
                'ordering': ['category', 'title'],
            },
        ),
    ]
