# Generated by Django 4.2.7 on 2025-08-02 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0017_cmselement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Test-Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('variant_a', models.JSONField(help_text='Original-Version der Landingpage', verbose_name='Variante A (Original)')),
                ('variant_b', models.JSONField(help_text='Test-Version der Landingpage', verbose_name='Variante B (Test)')),
                ('traffic_split', models.IntegerField(default=50, help_text='Prozent der Besucher, die Variante B sehen', verbose_name='Traffic-Split (%)')),
                ('start_date', models.DateTimeField(verbose_name='Start-Datum')),
                ('end_date', models.DateTimeField(verbose_name='End-Datum')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('active', 'Aktiv'), ('paused', 'Pausiert'), ('completed', 'Abgeschlossen')], default='draft', max_length=20, verbose_name='Status')),
                ('winner', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1, null=True, verbose_name='Gewinner')),
                ('confidence_level', models.FloatField(blank=True, null=True, verbose_name='Konfidenz-Level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'A/B Test',
                'verbose_name_plural': 'A/B Tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dealanalyticsevent',
            name='anonymized',
            field=models.BooleanField(default=True, verbose_name='Anonymisiert'),
        ),
        migrations.AddField(
            model_name='dealanalyticsevent',
            name='consent_given',
            field=models.BooleanField(default=False, verbose_name='Einverständnis erteilt'),
        ),
        migrations.AddField(
            model_name='dealanalyticsevent',
            name='element_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Element ID'),
        ),
        migrations.AddField(
            model_name='dealanalyticsevent',
            name='page_views',
            field=models.PositiveIntegerField(default=1, verbose_name='Seitenaufrufe'),
        ),
        migrations.AddField(
            model_name='dealanalyticsevent',
            name='position_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='X-Position'),
        ),
        migrations.AddField(
            model_name='dealanalyticsevent',
            name='position_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='Y-Position'),
        ),
        migrations.AddField(
            model_name='dealanalyticsevent',
            name='referrer',
            field=models.URLField(blank=True, null=True, verbose_name='Referrer'),
        ),
        migrations.AddField(
            model_name='dealanalyticsevent',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Session ID'),
        ),
        migrations.AddField(
            model_name='dealanalyticsevent',
            name='time_spent',
            field=models.DurationField(blank=True, null=True, verbose_name='Verbrachte Zeit'),
        ),
        migrations.AddField(
            model_name='dealanalyticsevent',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='dealanalyticsevent',
            name='visitor_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Wird anonymisiert gespeichert', null=True, verbose_name='Besucher IP'),
        ),
        migrations.AlterField(
            model_name='dealanalyticsevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Deal erstellt'), ('deleted', 'Deal gelöscht'), ('updated', 'Deal bearbeitet'), ('page_view', 'Seitenaufruf'), ('click', 'Klick'), ('scroll', 'Scroll'), ('download', 'Download'), ('form_submit', 'Formular-Submit'), ('time_spent', 'Zeit verbracht'), ('bounce', 'Bounce')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='dealanalyticsevent',
            index=models.Index(fields=['deal', 'event_type', 'timestamp'], name='deals_deala_deal_id_8113c6_idx'),
        ),
        migrations.AddIndex(
            model_name='dealanalyticsevent',
            index=models.Index(fields=['visitor_ip', 'timestamp'], name='deals_deala_visitor_bb5e84_idx'),
        ),
        migrations.AddField(
            model_name='abtest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='abtest',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='deals.deal', verbose_name='Dealroom'),
        ),
    ]
