# Generated by Django 5.2.4 on 2025-08-02 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="global_files/", verbose_name="Datei"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("hero_image", "Hero-Bild"),
                            ("logo", "Logo"),
                            ("gallery", "Galerie"),
                            ("document", "Dokument"),
                            ("video", "Video"),
                            ("data", "Daten"),
                            ("other", "Sonstiges"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Dateityp",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Hochgeladen am"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Öffentlich"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primär"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Tags"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Hochgeladen von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Globale Datei",
                "verbose_name_plural": "Globale Dateien",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
