# Generated by Django 5.2.4 on 2025-08-02 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalfile",
            name="tags",
        ),
        migrations.AddField(
            model_name="globalfile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
        ),
        migrations.AlterField(
            model_name="globalfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("hero_image", "Hero-Bild"),
                    ("logo", "Logo"),
                    ("gallery", "Galerie"),
                    ("document", "Dokument"),
                    ("video", "Video"),
                    ("other", "Sonstiges"),
                ],
                default="other",
                max_length=20,
                verbose_name="Dateityp",
            ),
        ),
        migrations.AlterField(
            model_name="globalfile",
            name="is_primary",
            field=models.BooleanField(
                default=False, verbose_name="Primär (für Hero/Logo)"
            ),
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Öffentlich"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="files.folder",
                        verbose_name="Übergeordneter Ordner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordner",
                "verbose_name_plural": "Ordner",
                "ordering": ["name"],
                "unique_together": {("name", "parent")},
            },
        ),
        migrations.AddField(
            model_name="globalfile",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="files.folder",
                verbose_name="Ordner",
            ),
        ),
    ]
