# Generated by Django 4.2.7 on 2025-08-03 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_remove_globalfile_tags_globalfile_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalfile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_global_files', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
    ]
